debug:
  config: true
  events: true
  saves: true

database:
  # 'yaml' only supported atm.
  implementation: yaml

speed-limit: 5.0

dehydration-distance: 3000.0
bucket-hydration: 0.5

abandoned-days: 14

abilities:
  speed:
    max-level: 30
    max-effort: 1000000.0
    effort-scale: 2000.0
    min-value: 0.174418605
    max-value: 0.3488372093
    
  jump:
    max-level: 20
    max-effort: 100000.0
    effort-scale: 2000.0
    min-value: 0.4
    max-value: 1.1

  health:
    max-level: 26
    max-effort: 10368.0
    effort-scale: 2700.0
    min-value: 15.0
    max-value: 40.0
  
