debug:
  config: true
  events: true
  saves: true
  scans: false
  finds: false

database:
  # 'yaml' only supported atm.
  implementation: yaml

speed-limit: 5.0

dehydration-distance: 3000.0
bucket-hydration: 1.0

abandoned-days: 14

scan:
  period-seconds: 60
  time-limit-micros: 500
  worlds:
    world: 3000
    world_nether: 3500
    world_the_end: 3000

abilities:
  speed:
    max-level: 30
    max-effort: 1000000.0
    effort-scale: 2000.0
    min-value: 0.174418605
    max-value: 0.3488372093
    
  jump:
    max-level: 20
    max-effort: 100000.0
    effort-scale: 2000.0
    min-value: 0.4
    max-value: 1.1

  health:
    max-level: 26
    max-effort: 10368.0
    effort-scale: 2700.0
    min-value: 15.0
    max-value: 40.0
  
