name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
main: nu.nerd.easyrider.EasyRider

permissions:
  easyrider.admin:
    description: Permission to administer the plugin.
    default: op

  easyrider.debug:
    description: Players with this permission receive debug messages.
    default: op

  easyrider.setlevel:
    description: Permission to use /horse-set-level.
    default: op

  easyrider.swap:
    description: Permission to use /horse-swap.
    default: op
    
  easyrider.tp:
    description: Permission to use /horse-tp.
    default: op
    
  easyrider.tphere:
    description: Permission to use /horse-tphere.
    default: op
    
  easyrider.bypass:
    description: Permission to use /horse-bypass.
    default: op
    
  easyrider.tame:
    description: Permission to use /horse-tame.
    default: op

  easyrider.free:
    description: Permission to use /horse-free.
    default: true

  easyrider.levels:
    description: Permission to use /horse-levels.
    default: true

  easyrider.upgrades:
    description: Permission to use /horse-upgrades.
    default: true
  
  easyrider.top:
    description: Permission to use /horse-top.
    default: true

  easyrider.speedlimit:
    description: Permission to use /horse-speed-limit.
    default: true

  easyrider.gps:
    description: Permission to use /horse-gps.
    default: true
   
  easyrider.gps-player:
    description: Permission to use /horse-gps <player>.
    default: op

  easyrider.access:
    description: Permission to use /horse-access.
    default: true

  easyrider.owned:
    description: Permission to use /horse-owned.
    default: true

  easyrider.owned-player:
    description: Permission to use /horse-owned <player>.
    default: op

commands:
  easyrider:
    description: ${project.name} administrative command.
    permission: easyrider.admin
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.
      §e/<command> migrate sqlite§f|§eyaml§f|§esqlite+yaml§f - Migrate the database to the specified implementation.

  horse-debug:
    description: Specify whether a horse will be subject to debug logging.
    permission: easyrider.debug
    usage: |
    
      §e/<command> §eon§f|§eoff§f - Turn debug logging on or off for the horse that was right-clicked.

  horse-set-level:
    description: Show ability level information for a horse.
    permission: easyrider.setlevel
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed <number>§f - Set the level of the specified ability on the right-clicked horse.

  horse-swap:
    description: Swap the stats of a specific horse with those of a clicked horse.
    permission: easyrider.swap
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §e<partial-uuid>§f - Swap the stats of the horse with the specified UUID with those of a clicked-on horse.

  horse-tp:
    description: Teleport to the horse with the specified UUID.
    permission: easyrider.tp
    aliases: ['htp']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §e<partial-uuid>§f - Teleport to the horse whose UUID begins with the specified prefix.

  horse-tphere:
    description: Teleport the horse with the specified UUID to the player.
    permission: easyrider.tphere
    aliases: ['htphere']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §e<partial-uuid>§f - Teleport the horse whose UUID begins with the specified prefix to you.

  horse-bypass:
    description: Toggle checks on your permission to access horses.
    permission: easyrider.bypass
    aliases: ['hbypass']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Toggle checks on your permission to access horses.

  horse-tame:
    description: Tame a horse to the specified player.
    permission: easyrider.tame
    aliases: ['htame']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> <player>§f - Tame a horse to the specified player.

  horse-free:
    description: Release a horse from your ownership.
    permission: easyrider.free
    aliases: ['hfree']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> [<uuid>]§f - Release a horse from your ownership. Either click on the horse, or specify it by its UUID.

  horse-levels:
    description: Show ability level information for a horse.
    permission: easyrider.levels
    aliases: ['horse-info', 'hinfo']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Show level information about the horse currently ridden or right-clicked.

  horse-upgrades:
    description: List all levels, corresponding attribute values and training effort for a specified ability.
    permission: easyrider.upgrades
    aliases: ['hup']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f - List all levels, corresponding attribute values and training effort for a specified ability.
      
  horse-top:
    description: List one page of 10 horses ranked in descending order by the specified ability.
    permission: easyrider.top
    aliases: ['htop']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f [§e<page>§f] - List one page of 10 horses ranked in descending order by the specified ability. If no page number is specified, it defaults to page 1.

  horse-speed-limit:
    description: 'Set or show your personal speed limit: the maximum speed (in m/s) that any horse you ride cannot exceed, even if it is capable of doing so.'
    permission: easyrider.speedlimit
    aliases: ['hlimit']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<number>§f] - Set your personal speed limit to <number> (in m/s), if specified, or show your current speed limit.

  horse-gps:
    description: Points you towards the last known location of a horse.
    permission: easyrider.gps
    aliases: ['hgps']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<player>§f] §e<number>§f|§e<name>§f|§e<uuid>§f - Point towards a horse owned by you or the specified player. The horse can be specified as a number in /horse-owned output, a match on the start of its name (if named with a name tag), or a match on the start of its UUID. The name can include spaces.

  horse-access:
    description: View or modify a horse's access list.
    permission: easyrider.gps
    aliases: ['haccess', 'hacl']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<partial-uuid>§f] (§e+§f|§e-§f)§e<player>§f... - View or modify a horse's access list. Either click on the horse or specify it by the start of its UUID. Players are added with '+' and removed with '-'. Multiple players can be added or removed in a single command.
      
      §6Example:
          §e/<command> 12abe4 -Alice +Bob§f - Give Bob access and revoke Alice's access to the horse whose UUID begins with 12abe4.   
          §e/<command> +Charles +Don§f - Give Charles and Don access to the next horse the owner right clicks on.   

  horse-owned:
    description: List information about all horses owned by you or a specified player.
    permission: easyrider.owned
    aliases: ['horse-list', 'hlist']
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<player>§f] [§e<page>§f] - List information about all horses owned by you or a specified player.
