name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
database: true
main: nu.nerd.easyrider.EasyRider

permissions:
  easyrider.admin:
    description: Permission to administer the plugin.
    default: op

  easyrider.debug:
    description: Players with this permission receive debug messages.
    default: op

  easyrider.setlevel:
    description: Permission to use /horse-set-level.
    default: op
    
  easyrider.levels:
    description: Permission to use /horse-levels.
    default: true

  easyrider.upgrades:
    description: Permission to use /horse-upgrades.
    default: true
  
  easyrider.top:
    description: Permission to use /horse-top.
    default: true

commands:
  easyrider:
    description: ${project.name} administrative command.
    permission: easyrider.admin
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.

  horse-debug:
    description: Specify whether a horse will be subject to debug logging.
    permission: easyrider.debug
    usage: |
    
      §e/<command> §eon§f|§eoff§f - Turn debug logging on or off for the horse that was right-clicked.

  horse-set-level:
    description: Show ability level information for a horse.
    permission: easyrider.setlevel
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed <number>§f - Set the level of the specified ability on the right-clicked horse.

  horse-levels:
    description: Show ability level information for a horse.
    permission: easyrider.levels
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Show level information about the horse currently ridden or right-clicked.

  horse-upgrades:
    description: List all levels, corresponding attribute values and training effort for a specified ability.
    permission: easyrider.upgrades
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f - List all levels, corresponding attribute values and training effort for a specified ability.
      
  horse-top:
    description: Show the top 10 horses for a specified ability.
    permission: easyrider.top
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f - Show the top 10 horses with the specified ability.
