name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
main: nu.nerd.easyrider.EasyRider

permissions:
  easyrider.admin:
    description: Permission to administer the plugin.
    default: op

  easyrider.debug:
    description: Players with this permission receive debug messages.
    default: op

  easyrider.setlevel:
    description: Permission to use /horse-set-level.
    default: op

  easyrider.swap:
    description: Permission to use /horse-swap.
    default: op
    
  easyrider.levels:
    description: Permission to use /horse-levels.
    default: true

  easyrider.upgrades:
    description: Permission to use /horse-upgrades.
    default: true
  
  easyrider.top:
    description: Permission to use /horse-top.
    default: true

  easyrider.speedlimit:
    description: Permission to use /horse-speed-limit.
    default: true

  easyrider.owned:
    description: Permission to use /horse-owned.
    default: true

  easyrider.owned-player:
    description: Permission to use /horse-owned <player>.
    default: op

commands:
  easyrider:
    description: ${project.name} administrative command.
    permission: easyrider.admin
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> reload§f - Reload the configuration.
      §e/<command> migrate sqlite§f|§eyaml§f|§esqlite+yaml§f - Migrate the database to the specified implementation.

  horse-debug:
    description: Specify whether a horse will be subject to debug logging.
    permission: easyrider.debug
    usage: |
    
      §e/<command> §eon§f|§eoff§f - Turn debug logging on or off for the horse that was right-clicked.

  horse-set-level:
    description: Show ability level information for a horse.
    permission: easyrider.setlevel
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed <number>§f - Set the level of the specified ability on the right-clicked horse.

  horse-swap:
    description: Swap the stats of a specific horse with those of a clicked horse.
    permission: easyrider.swap
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §e<partial-uuid>§f - Swap the stats of the horse with the specified UUID with those of a clicked-on horse.

  horse-levels:
    description: Show ability level information for a horse.
    permission: easyrider.levels
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command>§f - Show level information about the horse currently ridden or right-clicked.

  horse-upgrades:
    description: List all levels, corresponding attribute values and training effort for a specified ability.
    permission: easyrider.upgrades
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f - List all levels, corresponding attribute values and training effort for a specified ability.
      
  horse-top:
    description: List one page of 10 horses ranked in descending order by the specified ability.
    permission: easyrider.top
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §ehealth§f|§ejump§f|§espeed§f [§e<page>§f] - List one page of 10 horses ranked in descending order by the specified ability. If no page number is specified, it defaults to page 1.

  horse-speed-limit:
    description: 'Set or show your personal speed limit: the maximum speed (in m/s) that any horse you ride cannot exceed, even if it is capable of doing so.'
    permission: easyrider.speedlimit
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<number>§f] - Set your personal speed limit to <number> (in m/s), if specified, or show your current speed limit.

  horse-owned:
    description: List information about all horses owned by you or a specified player.
    permission: easyrider.owned
    usage: |
    
      §e/<command> help§f - Show usage help.
      §e/<command> §f[§e<player>§f] [<page>] - List information about all horses owned by you or a specified player.
